/* tslint:disable */
/* eslint-disable */
/**
 * Morning Night Guild - App Gateway
 * This is the AppGateway API documentation.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: morning.night.guild@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Article
 */
export interface Article {
    /**
     * id
     * @type {string}
     * @memberof Article
     */
    id?: string;
    /**
     * 記事のURL
     * @type {string}
     * @memberof Article
     */
    url?: string;
    /**
     * タイトル
     * @type {string}
     * @memberof Article
     */
    title?: string;
    /**
     * description
     * @type {string}
     * @memberof Article
     */
    description?: string;
    /**
     * サムネイルのURL
     * @type {string}
     * @memberof Article
     */
    thumbnail?: string;
    /**
     * タグ
     * @type {Array<string>}
     * @memberof Article
     */
    tags?: Array<string>;
}

/**
 * Check if a given object implements the Article interface.
 */
export function instanceOfArticle(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ArticleFromJSON(json: any): Article {
    return ArticleFromJSONTyped(json, false);
}

export function ArticleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Article {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'thumbnail': !exists(json, 'thumbnail') ? undefined : json['thumbnail'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
    };
}

export function ArticleToJSON(value?: Article | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'url': value.url,
        'title': value.title,
        'description': value.description,
        'thumbnail': value.thumbnail,
        'tags': value.tags,
    };
}

