/* tslint:disable */
/* eslint-disable */
/**
 * Morning Night Guild - App Gateway
 * This is the AppGateway API documentation.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: morning.night.guild@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Article } from './Article';
import {
    ArticleFromJSON,
    ArticleFromJSONTyped,
    ArticleToJSON,
} from './Article';

/**
 * 
 * @export
 * @interface ListArticleResponse
 */
export interface ListArticleResponse {
    /**
     * 
     * @type {Array<Article>}
     * @memberof ListArticleResponse
     */
    articles?: Array<Article>;
    /**
     * 次回リクエスト時に指定するページトークン
     * @type {string}
     * @memberof ListArticleResponse
     */
    nextPageToken?: string;
}

/**
 * Check if a given object implements the ListArticleResponse interface.
 */
export function instanceOfListArticleResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListArticleResponseFromJSON(json: any): ListArticleResponse {
    return ListArticleResponseFromJSONTyped(json, false);
}

export function ListArticleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListArticleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'articles': !exists(json, 'articles') ? undefined : ((json['articles'] as Array<any>).map(ArticleFromJSON)),
        'nextPageToken': !exists(json, 'nextPageToken') ? undefined : json['nextPageToken'],
    };
}

export function ListArticleResponseToJSON(value?: ListArticleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'articles': value.articles === undefined ? undefined : ((value.articles as Array<any>).map(ArticleToJSON)),
        'nextPageToken': value.nextPageToken,
    };
}

