name: cockroach terraform
description: cockroach terraform job. you should execute infra/setup action before.

inputs:
  project_env:
    description: "project env."
    required: true
  project_prefix:
    description: "project prefix."
    required: true
  action:
    description: "execution action : lint or plan or preview or deploy"
    required: true
  gcp_cloud_storage_terraform_bucket:
    description: "name of google cloud storage bucket for tfstate"
    required: true
  secret_cockroach_api_key:
    description: "secret of cockroach api key"
    required: true
  secret_cockroach_sql_user_password:
    description: "secret of cockroach sql user password"
    required: true
  working-directory:
    description: "working directory"
    default: ""

runs:
  using: composite
  steps:
    - name: Check action
      if: ${{ inputs.action != 'lint' && inputs.action != 'plan' && inputs.action != 'preview' && inputs.action != 'deploy' }}
      run: echo "invalid action ${{ inputs.action }}." && exit 1
      shell: sh

    - name: Download .tfstate file from GCS
      if: ${{ inputs.action == 'plan' || inputs.action == 'preview' || inputs.action == 'deploy' }}
      working-directory: ${{ inputs.working-directory }}
      run: gcloud storage cp gs://${{ inputs.gcp_cloud_storage_terraform_bucket }}/${{ inputs.project_env }}/cockroach/terraform.tfstate terraform.tfstate
      shell: sh

    - name: Terraform init
      working-directory: ${{ inputs.working-directory }}
      run: terraform init
      shell: sh
    
    - name: Terraform format
      if: ${{ inputs.action == 'lint' || inputs.action == 'preview' }}
      working-directory: ${{ inputs.working-directory }}
      run: terraform fmt -recursive -check
      shell: sh

    - name: Terraform validate
      if: ${{ inputs.action == 'lint' || inputs.action == 'preview' }}
      working-directory: ${{ inputs.working-directory }}
      run: terraform validate
      shell: sh

    - name: Terraform plan
      if: ${{ inputs.action == 'plan' || inputs.action == 'preview' }}
      working-directory: ${{ inputs.working-directory }}
      env: 
        COCKROACH_API_KEY: ${{ inputs.secret_cockroach_api_key }} 
      run: |
        terraform plan \
          -var='project_prefix=${{ inputs.project_prefix }}' \
          -var='project_env=${{ inputs.project_env }}' \
          -var='sql_user_password=${{ inputs.secret_cockroach_sql_user_password }}'
      shell: sh

    - name: Terraform apply
      if: ${{ inputs.action == 'deploy' || inputs.action == 'preview' }}
      working-directory: ${{ inputs.working-directory }}  
      env: 
        COCKROACH_API_KEY: ${{ inputs.secret_cockroach_api_key }} 
      run: |
        terraform apply \
          -auto-approve \
          -var='project_prefix=${{ inputs.project_prefix }}' \
          -var='project_env=${{ inputs.project_env }}' \
          -var='sql_user_password=${{ inputs.secret_cockroach_sql_user_password }}'
      shell: sh

    - name: Upload .tfstate file to GCS
      if: ${{ inputs.action == 'deploy' || inputs.action == 'preview' }}
      working-directory: ${{ inputs.working-directory }}
      run: gcloud storage cp terraform.tfstate gs://${{ inputs.gcp_cloud_storage_terraform_bucket }}/${{ inputs.project_env }}/cockroach/terraform.tfstate
      shell: sh
