name: set up go and aqua
description: set up go and go tool install by aqua

runs:
  using: composite
  steps:
    - name: Set up go
      uses: actions/setup-go@v3
      with:
        go-version-file: backend/go.mod

    - name: Set up aqua
      uses: aquaproj/aqua-installer@v1.1.2
      with:
        aqua_version: v1.19.2

    - name: Set up api go tool
      run: ${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua i
      working-directory: ./api
      shell: bash

    - name: Set up backend go tool
      run: ${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua i
      working-directory: ./backend
      shell: bash
