name: Setup node and yarn
description: use yarn
runs:
  using: composite
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Setup yarn
      run: npm install -g yarn
      shell: bash
    - name: Setup Buf
      uses: bufbuild/buf-setup-action@v1
      with:
        version: 'latest'
