name: set up node and yarn
description: use yarn

runs:
  using: composite
  steps:
    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Set up yarn
      run: npm install -g yarn
      shell: bash

    - name: Set up Buf
      uses: bufbuild/buf-setup-action@v1
      with:
        version : 'latest'
