name: test

on:
  pull_request:
    paths:
      - backend/**/*.go

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Go Test
        working-directory: ./backend
        run: go test ./...
