services:
  postgres:
    container_name: ${APP_NAME}-postgres
    image: postgres:${POSTGRES_VERSION}-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      TZ: UTC
      LANG: ja_JP.UTF-8
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
  migrate:
    container_name: ${APP_NAME}-migrate
    build:
      context: .
      dockerfile: migrate/Dockerfile
      args:
        GOLANG_VERSION: ${GOLANG_VERSION}
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    volumes:
      - ./migrate/go/pkg:/go/pkg
      - ../backend:/app
    restart: always
    depends_on:
      - postgres
  app-api:
    container_name: ${APP_NAME}-app-api
    build:
      context: .
      dockerfile: appapi/Dockerfile
      args:
        GOLANG_VERSION: ${GOLANG_VERSION}
    ports:
      - ${APP_API_PORT}:8080
    environment:
      ENV: ${ENV}
      API_KEY: local
      APP_CORE_URL: http://app-core:8080
      NEWRELIC_APP_NAME: ${NEWRELIC_APP_NAME}
      NEWRELIC_LICENSE: ${NEWRELIC_LICENSE}
      CORS_ALLOW_ORIGINS: http://localhost:5173
      CORS_DEBUG_ENABLE: true
    volumes:
      - ./appapi/go/pkg:/go/pkg
      - ../backend:/app
    restart: always
    depends_on:
      - app-core
  app-core:
    container_name: ${APP_NAME}-app-core
    build:
      context: .
      dockerfile: appcore/Dockerfile
      args:
        GOLANG_VERSION: ${GOLANG_VERSION}
    ports:
      - ${APP_CORE_PORT}:8080
    environment:
      ENV: ${ENV}
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      API_KEY: local
      NEWRELIC_APP_NAME: ${NEWRELIC_APP_NAME}
      NEWRELIC_LICENSE: ${NEWRELIC_LICENSE}
    volumes:
      - ./appcore/go/pkg:/go/pkg
      - ../backend:/app
    restart: always
    depends_on:
      - postgres
  core:
    container_name: ${APP_NAME}-core
    build:
      context: .
      dockerfile: core/Dockerfile
      args:
        GOLANG_VERSION: ${GOLANG_VERSION}
    ports:
      - ${APP_PORT}:8080
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      API_KEY: local
      ENV: ${ENV}
      NEWRELIC_APP_NAME: ${NEWRELIC_APP_NAME}
      NEWRELIC_LICENSE: ${NEWRELIC_LICENSE}
      CORS_ALLOW_ORIGINS: http://localhost:5173
      CORS_DEBUG_ENABLE: true
    volumes:
      - ./core/go/pkg:/go/pkg
      - ../backend:/app
    restart: always
    depends_on:
      - postgres
  web:
    container_name: ${APP_NAME}-web
    build:
      context: .
      dockerfile: web/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    ports:
      - ${WEB_PORT}:5173
    environment:
      VITE_SERVICE_ENDPOINT: http://localhost:${APP_API_PORT}
    volumes:
      - ../frontend:/app
    restart: always
