options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: "gcr.io/$PROJECT_ID/builder"
    script: |
      aqua i
      buf generate --template buf.backend.gen.yaml
    dir: "api"
  - name: "gcr.io/$PROJECT_ID/deployer"
    env:
      - "KO_DOCKER_REPO=gcr.io/$PROJECT_ID"
      - "REVISION_SERVICE_ACCOUNT=$_REVISION_SERVICE_ACCOUNT"
      - "API_KEY=${_API_KEY}:latest"
    script: |
      gcloud run \
      deploy slack-receiver \
      --image $(SOURCE_DATE_EPOCH=$(date +%s) ko build ./) \
      --region asia-northeast1 \
      --cpu 1 \
      --memory 128Mi \
      --max-instances 1 \
      --service-account $REVISION_SERVICE_ACCOUNT \
      --set-secrets API_KEY=$API_KEY \
      --allow-unauthenticated
    dir: "backend/app/slack"
