name: gcp terraform
description: deploy gcp terraform infra. you should execute infra/setup action before.

inputs:
  project_env:
    description: "project env."
    required: true
  project_prefix:
    description: "project prefix."
  action:
    description: "execution action : lint or plan or preview or deploy"
    required: true
  gcp_project_id:
    description: "gcp project id"
    required: true
  gcp_cloud_storage_terraform_bucket:
    description: "name of google cloud storage bucket for tfstate"
    required: true
  secret_core_api_key:
    description: "secret of core api key"
    required: true
  secret_core_database_url:
    description: "secret of database url"
    required: true  
  working-directory:
    description: "working directory"
    default: ""

runs:
  using: composite
  steps:
    - name: Check action
      if: ${{ inputs.action != 'lint' && inputs.action != 'plan' && inputs.action != 'preview' && inputs.action != 'deploy' }}
      run: echo "invalid action ${{ inputs.action }}." && exit 1
      shell: sh

    - name: Download .tfstate file from GCS
      if: ${{ inputs.action == 'plan' || inputs.action == 'preview' || inputs.action == 'deploy' }}
      working-directory: ${{ inputs.working-directory }}
      run: gcloud storage cp gs://${{ inputs.gcp_cloud_storage_terraform_bucket }}/${{ inputs.project_env }}/gcp/terraform.tfstate terraform.tfstate
      shell: sh

    - name: Terraform init
      working-directory: ${{ inputs.working-directory }}
      run: terraform init
      shell: sh
    
    - name: Terraform format
      if: ${{ inputs.action == 'lint' || inputs.action == 'preview' }}
      working-directory: ${{ inputs.working-directory }}
      run: terraform fmt -recursive -check
      shell: sh
    
    - name: Terraform validate
      if: ${{ inputs.action == 'lint' || inputs.action == 'preview' }}
      working-directory: ${{ inputs.working-directory }}
      run: terraform validate
      shell: sh

    - name: Terraform plan
      if: ${{ inputs.action == 'plan' || inputs.action == 'preview' }}
      working-directory: ${{ inputs.working-directory }}
      run: |
        terraform plan \
          -var='project_prefix=${{ inputs.project_prefix }}' \
          -var='project_env=${{ inputs.project_env }}' \
          -var='gcp_credentials_file_path=${{ env.GOOGLE_APPLICATION_CREDENTIALS }}' \
          -var='project_id=${{ inputs.gcp_project_id }}' \
          -var='secret_core_api_key=${{ inputs.secret_core_api_key }}' \
          -var='secret_core_database_url=${{ inputs.secret_core_database_url }}'
      shell: sh

    - name: Terraform apply
      if: ${{ inputs.action == 'deploy' || inputs.action == 'preview' }}
      working-directory: ${{ inputs.working-directory }}          
      run: |
        terraform apply \
          -auto-approve \
          -var='project_prefix=${{ inputs.project_prefix }}' \
          -var='project_env=${{ inputs.project_env }}' \
          -var='gcp_credentials_file_path=${{ env.GOOGLE_APPLICATION_CREDENTIALS }}' \
          -var='project_id=${{ inputs.gcp_project_id }}' \
          -var='secret_core_api_key=${{ inputs.secret_core_api_key }}' \
          -var='secret_core_database_url=${{ inputs.secret_core_database_url }}'
      shell: sh

    - name: Upload .tfstate file to GCS
      if: ${{ inputs.action == 'deploy' || inputs.action == 'preview' }}
      working-directory: ${{ inputs.working-directory }}
      run: gcloud storage cp terraform.tfstate gs://${{ inputs.gcp_cloud_storage_terraform_bucket }}/${{ inputs.project_env }}/gcp/terraform.tfstate
      shell: sh
