name: api document

on:
  push:
    branches:
      - main
    paths:
      - api/**/*.proto
      - backend/adapter/gateway/ent/schema/*.go
  pull_request:

jobs:
  document:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: ./.github/actions/go
      - name: Set up tbls
        run: go install github.com/k1LoW/tbls@main
      - name: Set up protoc
        uses: arduino/setup-protoc@v1
      - name: Generate connect code
        working-directory: ./api
        run: buf generate
      - name: Go Generate
        working-directory: ./backend
        run: go generate ./...
      - name: Set up wire
        working-directory: ./backend
        run: wire
      - name: Database migrate
        working-directory: ./backend
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
        run: go run cmd/migrate/main.go
      - name: Generate database document
        run: tbls doc "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable" public/database
      - name: Generate api document
        working-directory: .
        run: |
          go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest
          mkdir -p public/api
          protoc --doc_out=./public/api --doc_opt=markdown,README.md $(find api -name '*.proto') 
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
