name: api lint
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    paths:
      - .github/workflows/api.lint.yaml
      - api/**/*.proto
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: backend/go.mod
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.0.2
        with:
          aqua_version: v1.32.1
      - name: Setup api go tool
        working-directory: ./api
        run: ${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua i
      - name: Buf lint
        working-directory: ./api/proto
        run: buf lint
      - name: Buf format
        working-directory: ./api
        run: buf format -d --exit-code
