name: backend test

on:
  pull_request:
    paths:
      - .github/actions/backend/setup/action.yml
      - .github/workflows/backend.test.yml
      - backend/**/*.go
      - backend/go.mod
      - backend/go.sum

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: backend/go.mod

      - name: Go Test
        working-directory: ./backend
        run: go test ./...
