name: backend vulnerability

on:
  pull_request:
    paths:
      - backend/**

defaults:
  run:
    working-directory: backend

jobs:
  vulnerability:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: backend/go.mod
      - name: Write Go list
        run: go list -json -m all > go.list
      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main
        with:
          goListFile: backend/go.list
