name: backend lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: ./.github/actions/go
      - name: Generate connect code
        working-directory: ./api
        run: buf generate
      - name: Go Generate
        working-directory: ./backend
        run: go generate ./...
      - name: Set up wire
        working-directory: ./backend
        run: wire
      - name: Golangci lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          skip-pkg-cache: true
          working-directory: ./backend
