name: backend lint

on:
  pull_request:
    paths:
      - .github/actions/backend/setup/action.yml
      - .github/workflows/backend.lint.yml
      - backend/**/*.go
      - backend/.golangci.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up backend
        uses: ./.github/actions/backend/setup

      - name: Golangci lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          skip-pkg-cache: true
          working-directory: ./backend
