name: backend test

on:
  pull_request:
    paths:
      - backend/**/*.go

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: backend/go.mod
      - name: Set up connect
        run: |
          go install github.com/bufbuild/buf/cmd/buf@latest
          go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install github.com/bufbuild/connect-go/cmd/protoc-gen-connect-go@latest
      - name: Generate connect code
        working-directory: ./api
        run: buf generate
      - name: Go Test
        working-directory: ./backend
        run: | 
          go generate ./...
          go test ./...
