name: backend test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: backend/go.mod
      - name: Set up connect
        run: |
          go install github.com/bufbuild/buf/cmd/buf@latest
          go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install github.com/bufbuild/connect-go/cmd/protoc-gen-connect-go@latest
      - name: Generate connect code
        working-directory: ./api
        run: buf generate
      - name: Go Generate
        working-directory: ./backend
        run: go generate ./...
      - name: Set up wire
        working-directory: ./backend
        run: |
          go install github.com/google/wire/cmd/wire@latest
          wire
      - name: Go Test
        working-directory: ./backend
        run: go test ./...
      - name: Coverage
        working-directory: ./backend
        run: |
          go test ./...  -coverpkg=./... -coverprofile ./coverage_temp.txt
          cat coverage_temp.txt | grep -v "/ent/" | grep -v "/driver/" | grep -v "/cmd/" > coverage.txt
          rm coverage_temp.txt
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
