name: backend lint

on:
  pull_request:
    paths:
      - backend/**/*.go
      - backend/.golangci.yml

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: backend/go.mod
      - name: Set up connect
        run: |
          go install github.com/bufbuild/buf/cmd/buf@latest
          go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install github.com/bufbuild/connect-go/cmd/protoc-gen-connect-go@latest
      - name: Generate connect code
        working-directory: ./api
        run: buf generate
      - name: Go Generate
        working-directory: ./backend
        run: go generate ./...
      - name: Set up wire
        working-directory: ./backend
        run: |
          go install github.com/google/wire/cmd/wire@latest
          wire
      - name: Golangci lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          skip-pkg-cache: true
          working-directory: ./backend
