name: backend lint
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    paths:
      - .github/workflows/backend.lint.yaml
      - backend/**/*.go
      - backend/.golangci.yaml
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: backend/go.mod
      - name: Go build
        working-directory: ./backend
        run: go build ./...
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.0.2
        with:
          aqua_version: v1.32.3
      - name: Setup backend go tool
        working-directory: ./backend
        run: ${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua i
      - name: Golangci lint
        working-directory: ./backend
        run: golangci-lint run --fix
