name: backend unit test
on:
  pull_request:
    paths:
      - .github/workflows/backend.test.unit.yaml
      - backend/**/*.go
      - backend/go.mod
      - backend/go.sum
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: backend/go.mod
      - name: Go Test
        working-directory: ./backend
        run: go test ./internal/...
