name: frontend diff
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    paths:
      - .github/workflows/frontend.diff.yaml
      - api/**/*.proto
      - api/openapi.yaml
jobs:
  diff:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: backend/go.mod
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.0.2
        with:
          aqua_version: v1.33.0
      - name: Setup api go tool
        working-directory: ./api
        run: ${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua i
      - name: Generate connect code
        working-directory: ./api
        run: |
          npm install
          buf generate --template buf.frontend.gen.yaml
      - name: Generate openapi code
        working-directory: ./api
        run: |
          docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i /local/openapi.yaml -g typescript-fetch -o /local/openapi
          sudo rm -r ../frontend/src/openapi && sudo mv openapi ../frontend/src/openapi
      - name: Check diff
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git status --porcelain;
            exit 1;
          else
            echo "no changes";
          fi
