name: frontend lint
run-name: ${{ github.ref_name }} by @${{ github.actor }} ${{ github.workflow }}
on:
  pull_request:
    paths:
      - .github/actions/frontend/setup/action.yaml
      - .github/workflows/frontend.lint.yaml
      - frontend/*
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup frontend
        uses: ./.github/actions/frontend/setup
      - name: Install
        working-directory: ./frontend
        run: yarn install
      - name: Generate connect code
        working-directory: ./api
        run: |
          npm install
          buf generate --template buf.frontend.gen.yaml
      - name: Build
        working-directory: ./frontend
        run: yarn build
      - name: Lint
        working-directory: ./frontend
        run: yarn xo
