name: infra image clean

on:
  schedule:
    - cron: '0 19 * * *'

permissions:
  id-token: write
  contents: read

jobs:
  clean:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_FOR_GCR }}
          audience: https://github.com/morning-night-dream

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Set up docker auth
        run: gcloud auth configure-docker

      - name: Image clean
        uses: docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli
        with:
          args: >-
            -repo=${{ secrets.GCP_DOCKER_REPO }}/core
            -repo=${{ secrets.GCP_DOCKER_REPO }}/slack
