name: yaml lint
run-name: ${{ github.ref_name }} by @${{ github.actor }} [ ${{ github.workflow }} ]
on:
  pull_request:
    paths:
      - "**/*.yaml"
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.0.2
        with:
          aqua_version: v1.32.0
      - name: Setup tool
        run: ${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua i
      - name: Yaml format lint
        run: yamlfmt -lint
